


                           ''''''''''''''''''''   Theoretical Questions   ''''''''''''''''''''




Q1) Explain the purpose and advantages of NumPy in scientific computing and data analysis. How does it enhance Python's capabilities for numerical operations?


Ans) NumPy (Numerical Python) is a powerful library for scientific computing and data analysis in Python. It provides a range of tools for working with large multi-dimensional arrays and matrices, along with an extensive collection of mathematical functions. Its primary purpose is to enable efficient and fast numerical operations, which are essential in scientific computing and data analysis tasks.


Purpose of NumPy:

Efficient Arrays: NumPy's ndarray object provides compact, memory-efficient arrays, outperforming Python lists in speed and storage.

Mathematical Functions: It includes functions for linear algebra, statistics, and more, optimized for working on entire arrays without loops.

Library Integration: NumPy is foundational for libraries like SciPy, pandas, and TensorFlow, facilitating efficient data handling.

Broadcasting: It supports operations on arrays of different shapes without creating extra data, improving performance in multidimensional tasks.


Advantages of NumPy:

Speed & Efficiency: NumPy is faster than Python lists, thanks to its C implementation. It also supports vectorized operations, reducing the need for loops and speeding up computations.

Memory Efficiency: NumPy arrays use less memory than Python lists by storing elements in contiguous memory locations, making data retrieval and processing more efficient.

Multidimensional Data Handling: NumPy supports n-dimensional arrays (ndarray), offering advanced slicing and indexing for easy manipulation of complex data structures.

Mathematical Functions: It provides key functions for matrix multiplication, eigenvalue computation, Fourier transforms, and other linear algebra tasks essential for scientific computing and machine learning.

Interoperability: NumPy integrates easily with C, C++, and Fortran, optimizing performance for heavy computations.

Library Integration: Many scientific libraries like pandas, SciPy, and TensorFlow rely on NumPy arrays, ensuring seamless data interoperability.

Enhancing Python's Numerical Capabilities:

Without NumPy, Python's default data structures like lists and dictionaries are not optimized for numerical calculations. While Python is a powerful programming language, it is not inherently optimized for heavy mathematical computations, especially when working with large datasets or performing complex operations like matrix multiplications or solving systems of linear equations.

NumPy enhances Python's numerical capabilities by:

Providing highly efficient data structures (arrays) for storing and manipulating numerical data.
Reducing the need for loops in mathematical operations (using vectorization).
Offering a wide range of mathematical functions optimized for performance.
Allowing more control over data types, which helps in handling different precision requirements for numerical tasks.

Q2)  Compare and contrast np.mean() and np.average() functions in NumPy. When would you use one over the  other?

Ans) In NumPy, both np.mean() and np.average() are used to compute the central tendency of an array, but they differ in their behavior and applications. Here's a comparison:

1. Basic Difference:
np.mean():

Purpose: Computes the arithmetic mean (average) of the array elements.
Weights: Does not take any weights into account; all values are treated equally.
Usage: Use when you need a simple mean calculation.


np.average():

Purpose: Computes a weighted average of the array elements.
Weights: Accepts an optional weights parameter, which allows each element to contribute differently to the result.
Usage: Use when you need to calculate a weighted mean or when you want more control over how elements contribute to the average.


2. Parameters:
np.mean():

Syntax: np.mean(a, axis=None, dtype=None, out=None, keepdims=False)
Takes the average over the specified axis (default is all elements).
Returns the unweighted mean of the array elements.


np.average():

Syntax: np.average(a, axis=None, weights=None, returned=False)
Takes an additional weights parameter. If weights is not provided, it behaves the same as np.mean().
Can return both the weighted average and the sum of weights if returned=True.


3. Weighted Average:
np.mean(): Does not support weighting, so it computes the simple mean.
np.average(): Supports weighting via the weights argument, allowing you to calculate a weighted average where some values have more influence than others.


5. Performance:
When weights are not needed, np.mean() is slightly faster and more efficient because it doesn’t involve additional computations for weights.
When you need to apply weights, np.average() is the appropriate function to use.

In [3]:
''' Q3) Describe the methods for reversing a NumPy array along different axes. Provide examples for 1D and 2D  arrays.
Ans) Reversing a NumPy array along different axes can be done using several methods that allow control over which axis is reversed, depending on 
whether the array is one-dimensional (1D), two-dimensional (2D), or higher-dimensional. Here are the key methods, followed by theoretical explanations 
and examples for 1D and 2D arrays.

1. Reversing Using Slicing ([::-1])
Theory:
Slicing in Python and NumPy allows selecting elements from an array or list with a specified step size. The slicing syntax [::-1] reverses the array 
because the -1 indicates that the step size is negative, which effectively traverses the array from the last element to the first.

For 1D arrays, [::-1] reverses the order of elements.
For 2D arrays, slicing can be applied along each axis:
[::-1] reverses the rows (i.e., it flips the array vertically).
[:, ::-1] reverses the columns (i.e., it flips the array horizontally).
Examples: '''

# 1D Array:
import numpy as np
arr_1d = np.array([1, 2, 3, 4, 5])
reversed_1d = arr_1d[::-1]
print (reversed_1d)

print("________________________________")

# 2D Array (Reversing Rows):
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
reversed_rows = arr_2d[::-1]
print (reversed_rows)

print("________________________________")

# 2D Array (Reversing Columns):
reversed_columns = arr_2d[:, ::-1]
print(reversed_columns)

print("________________________________")

''' 2. Using np.flip():
np.flip() allows you to reverse an array along a specified axis. '''

# 1D Array Example:
 
reversed_1d_flip = np.flip(arr_1d)
print(reversed_1d_flip)

print("________________________________")

# 2D Array Example (Reverse along both axes):

reversed_2d_flip = np.flip(arr_2d)
print(reversed_2d_flip)

print("________________________________")

# 2D Array Example (Reverse only rows):

reversed_rows_flip = np.flip(arr_2d, axis=0)
print(reversed_rows_flip)

print("________________________________")

# 2D Array Example (Reverse only columns):

reversed_columns_flip = np.flip(arr_2d, axis=1)
print(reversed_columns_flip)

print("________________________________")

''' 3. Using np.flipud() and np.fliplr():
np.flipud() flips an array along the vertical axis (up/down).
np.fliplr() flips an array along the horizontal axis (left/right). '''

# 2D Array Example (Vertical Flip):

flipped_ud = np.flipud(arr_2d)
print(flipped_ud)

print("________________________________")

# 2D Array Example (Horizontal Flip):

flipped_lr = np.fliplr(arr_2d)
print(flipped_lr)



[5 4 3 2 1]
________________________________
[[7 8 9]
 [4 5 6]
 [1 2 3]]
________________________________
[[3 2 1]
 [6 5 4]
 [9 8 7]]
________________________________
[5 4 3 2 1]
________________________________
[[9 8 7]
 [6 5 4]
 [3 2 1]]
________________________________
[[7 8 9]
 [4 5 6]
 [1 2 3]]
________________________________
[[3 2 1]
 [6 5 4]
 [9 8 7]]
________________________________
[[7 8 9]
 [4 5 6]
 [1 2 3]]
________________________________
[[3 2 1]
 [6 5 4]
 [9 8 7]]


Q4)  How can you determine the data type of elements in a NumPy array? Discuss the importance of data types in memory management and performance.

Ans) To determine the data type of elements in a NumPy array, you can use the following methods:

dtype Attribute:

The dtype attribute of a NumPy array provides the data type of the elements stored in the array.
Example:

import numpy as np
arr = np.array([1, 2, 3])
print(arr.dtype) 

np.array() and dtype Parameter:

When creating a NumPy array, you can explicitly set the data type using the dtype parameter. This is useful for controlling the data type and ensuring compatibility with specific numerical operations.
Example:
arr = np.array([1, 2, 3], dtype=np.float64)
print(arr.dtype)


astype() Method:

The astype() method can be used to convert the data type of the elements in the array to another type. This is also a way to examine and manipulate the data type of an array.
Example:
arr = np.array([1.0, 2.0, 3.0])
new_arr = arr.astype(int)
print(new_arr.dtype)


Importance of Data Types in NumPy
1. Memory Management:
Data types (or dtype in NumPy) define how much memory is allocated for each element of an array. Each data type specifies the size of the data in bytes, and choosing the correct data type has a significant impact on memory usage:

Smaller data types save memory: For example, int8 (8-bit integer) uses 1 byte per element, while int64 (64-bit integer) uses 8 bytes per element. For large arrays, choosing a smaller data type can drastically reduce memory consumption.

Higher precision uses more memory: Data types like float64 (64-bit floating point) consume more memory than float32 (32-bit floating point). Using high precision where not necessary can lead to inefficient memory use.

Efficient use of memory is critical in large datasets: When working with millions of data points (e.g., in machine learning or big data analytics), selecting the appropriate data type ensures that memory is used efficiently, preventing unnecessary memory allocation or memory overflow.

2. Performance Optimization:
The data type of a NumPy array also impacts the performance of operations:

Faster computation with lower precision types: Operations involving lower precision data types (like int16 or float32) are faster because they require less computation and bandwidth compared to higher precision types (like int64 or float64). For tasks that do not need high precision, this leads to significant performance gains.

Hardware-level optimization: NumPy arrays are implemented in C, and NumPy leverages low-level optimization (SIMD instructions) that is tuned to the array's data type. This allows NumPy to perform operations like element-wise addition, multiplication, and matrix transformations very quickly, especially when the data type matches the underlying hardware architecture.

Cache efficiency: Choosing smaller data types allows more elements to fit into the CPU cache, improving cache performance. This is critical when performing repeated operations on large datasets.

3. Numerical Precision:
Data types also determine the precision of numerical operations:

Precision errors in floating-point operations: Using data types with lower precision (e.g., float32 vs. float64) can lead to rounding errors in numerical computations. In scientific computing, simulations, or machine learning tasks where numerical accuracy is paramount, using the appropriate data type ensures that calculations remain accurate.

Integer overflow/underflow: Choosing an integer data type that is too small (e.g., int8 or int16) can result in overflow or underflow if values exceed the range that the data type can store. Ensuring the right data type is crucial for avoiding these errors.

Q5)  Define ndarrays in NumPy and explain their key features. How do they differ from standard Python lists?
Ans) What are ndarrays in NumPy?
In NumPy, an ndarray (N-dimensional array) is the core data structure used to store and manipulate numerical data. It is a grid-like structure that holds items of the same data type, typically numbers, arranged in multiple dimensions. These arrays are homogeneous, meaning every element in the array must be of the same type, and they allow for fast and efficient numerical operations.

Key Features of ndarrays
Multidimensional Support:

An ndarray can have any number of dimensions, from 1D (like a vector) to 2D (like a matrix), to higher dimensions (n-dimensional arrays).

Homogeneous Data Types:

All elements in an ndarray must have the same data type (e.g., int32, float64), ensuring memory efficiency and fast operations.

Memory Efficiency:

ndarrays are stored in contiguous blocks of memory, unlike Python lists which are arrays of pointers to objects. This makes them much more memory-efficient and faster to access.
The dtype attribute specifies the data type of the array, which helps NumPy optimize memory use.
Vectorized Operations:

Operations on ndarrays are performed element-wise, without the need for explicit loops. This concept, known as vectorization, allows for fast and efficient computations.

Broadcasting:

NumPy allows arithmetic operations on arrays of different shapes, automatically "broadcasting" the smaller array over the larger array to make the operation compatible.

Slicing and Indexing:

ndarrays support advanced slicing and indexing, allowing you to efficiently select and manipulate specific elements, rows, columns, or sub-arrays.

Support for Mathematical Functions:

NumPy provides a wide array of mathematical, statistical, and linear algebra functions that operate on ndarrays, making them a powerful tool for scientific computing and data analysis.

Shape and Size Attributes:

The shape attribute indicates the dimensions of the array (e.g., 2x3 for a 2D array with 2 rows and 3 columns).
The size attribute provides the total number of elements in the array.

How ndarrays Differ from Python Lists
Memory Efficiency:

Python lists are collections of references to objects, meaning each element in a list is a pointer to an object stored elsewhere in memory. In contrast, ndarrays store elements in contiguous memory, which is far more efficient, especially for large datasets.
NumPy arrays use less memory because the data is stored in a fixed type and in compact form.
Homogeneity:

Python lists can store elements of different data types (e.g., integers, floats, strings). ndarrays, however, require all elements to be of the same type, which allows NumPy to optimize storage and performance.
Performance (Speed):

Due to contiguous memory storage and vectorized operations, ndarrays are significantly faster than Python lists for numerical and mathematical computations. Python lists require explicit loops for such operations, which are slower.
Vectorized Operations:

Operations on NumPy arrays are applied element-wise without the need for looping (i.e., vectorized). Python lists require explicit loops to perform element-wise operations, which are slower and more complex.

NumPy arrays can perform operations with arrays of different shapes through broadcasting, making mathematical operations flexible. Python lists don't support broadcasting and would require explicit loops to achieve the same result.
Built-in Functions for Arrays:

NumPy provides a vast collection of optimized mathematical, statistical, and algebraic functions that work directly on arrays, which Python lists do not support. For example, functions like np.sum(), np.mean(), and np.dot() make complex operations easy and efficient with ndarrays.

Q6)  Analyze the performance benefits of NumPy arrays over Python lists for large-scale numerical operations.

Ans) NumPy arrays offer significant performance benefits over Python lists for large-scale numerical operations due to:

Memory Efficiency: NumPy arrays store elements in contiguous memory blocks, using less memory compared to Python lists, which store pointers to objects. This makes data retrieval and processing faster.

Vectorization: NumPy supports element-wise operations without explicit loops (vectorization), enabling fast, low-level execution, whereas Python lists require slow, explicit iteration.

Optimized Mathematical Functions: NumPy provides a suite of optimized, pre-built mathematical functions that operate efficiently on arrays, reducing the need for manual implementation.

Broadcasting: NumPy arrays can handle operations between arrays of different shapes via broadcasting, simplifying and speeding up computation without extra memory overhead.

NumPy arrays provide faster computation, efficient memory usage, and better scalability, making them ideal for large-scale numerical operations.

In [12]:
''' Q7) Compare vstack() and hstack() functions in NumPy. Provide examples demonstrating their usage and  output.

Ans) Comparison of vstack() and hstack() in NumPy:
vstack() (Vertical Stack): Combines arrays by stacking them vertically (row-wise). The arrays must have the same number of columns.

hstack() (Horizontal Stack): Combines arrays by stacking them horizontally (column-wise). The arrays must have the same number of rows.

Examples:'''
# vstack() Example:

import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.vstack((arr1, arr2))
print(result)

print("______________________")

# hstack() Example:

import numpy as np
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
result = np.hstack((arr1, arr2))
print(result)


#vstack() stacks arrays along the vertical axis (adds rows).
#hstack() stacks arrays along the horizontal axis (adds columns).

[[1 2]
 [3 4]]
______________________
[1 2 3 4]


In [28]:
''' Q8) Explain the differences between fliplr() and flipud() methods in NumPy, including their effects on various  array dimensions.


Ans) In NumPy, both fliplr() and flipud() are used to reverse the order of elements in a 2D array, but they operate along different axes:

1. fliplr() (Flip Left to Right):
Purpose: Reverses the elements in each row of a 2D array, flipping the array along the vertical axis (left to right).

Effect: It flips the array horizontally, leaving the row order unchanged but reversing the content of each row.

Applicable: For 2D arrays with at least two columns.
Example: '''

import numpy as np
arr = np.array([[1, 2, 3], [4, 5, 6]])
result = np.fliplr(arr)
print(result)

print("______________________")

''' 2. flipud() (Flip Up to Down):
Purpose: Reverses the order of rows in a 2D array, flipping the array along the horizontal axis (up to down).

Effect: It flips the array vertically, reversing the row order but leaving the content of each row unchanged.

Applicable: For 2D arrays with at least two rows.
Example: '''

arr = np.array([[1, 2, 3],
                [4, 5, 6]])
result = np.flipud(arr)
print(result)


#Key Differences:
#fliplr(): Flips the elements within each row, reflecting the array horizontally (left-right).

#flipud(): Flips the rows themselves, reflecting the array vertically (up-down).

#In summary, fliplr() changes the order of elements in rows, while flipud() changes the order of rows themselves.

[[3 2 1]
 [6 5 4]]
______________________
[[4 5 6]
 [1 2 3]]


In [26]:
''' Q9)  Discuss the functionality of the array_split() method in NumPy. How does it handle uneven splits?

Ans) The array_split() method in NumPy is used to split an array into multiple sub-arrays. It is a flexible version of the split() method, especially useful when the array cannot be evenly divided.

Functionality of array_split()
Basic Use: It splits an array into a specified number of sub-arrays. You can define how many parts you want the array to be split into.
Uneven Splits: If the array size is not divisible by the number of parts, array_split() will handle the remainder by distributing extra elements into some of the sub-arrays. The first sub-arrays will have one more element than the others to accommodate the unevenness.
How It Handles Uneven Splits:
When the number of elements in the array is not divisible by the number of splits:

Larger sub-arrays are created for the initial splits, containing one more element than the later sub-arrays. '''
#Example

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7])
result = np.array_split(arr, 3)
print(result)


#In the example, array_split(arr, 3) splits the 7-element array into 3 parts. Since 7 cannot be divided evenly by 3:

#The first sub-array has 3 elements,
#The second and third sub-arrays each have 2 elements.
#Comparison with split():
#If you use split(), it will raise an error when the array cannot be evenly split, unlike array_split(), which handles uneven cases gracefully.

[array([1, 2, 3]), array([4, 5]), array([6, 7])]


In [38]:
''' Q10)  Explain the concepts of vectorization and broadcasting in NumPy. How do they contribute to efficient array
operations?
Ans) Vectorization:
Concept: Vectorization refers to performing operations directly on entire arrays (or vectors) without the need for explicit loops. In NumPy, operations like addition, multiplication, and other mathematical functions are applied element-wise to entire arrays at once.
Benefit: It leverages low-level optimizations, making operations faster by eliminating Python loops and allowing NumPy to use highly efficient C-based implementations.
Example: '''

import numpy as np
arr = np.array([1, 2, 3])
result = arr * 2 
print(result)

print("____________________")

''' Broadcasting:
Concept: Broadcasting allows NumPy to perform operations on arrays of different shapes by automatically expanding the smaller array to match the shape of the larger one. This enables operations without creating large temporary arrays, saving memory and computation time.
Benefit: It simplifies code and allows for efficient computation on arrays with different dimensions.
Example: '''

arr = np.array([[1, 2, 3], [4, 5, 6]])
vec = np.array([1, 2, 3])
result = arr + vec
print(result)


''' Contribution to Efficiency:
Vectorization speeds up operations by using optimized internal code.
Broadcasting reduces memory usage and simplifies computations by avoiding redundant data expansion.
Together, they make array operations in NumPy much faster and more efficient. '''

print("____________________")

[2 4 6]
____________________
[[2 4 6]
 [5 7 9]]
____________________


                 '''''''''''''''''''''''''   Practical Questions   '''''''''''''''''''''''''

Q1)  Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

Ans) 

In [42]:
import numpy as np
arr = np.random.randint(1, 101, size=(3, 3))
transposed_arr = arr.T
arr, transposed_arr


(array([[60, 69, 96],
        [85,  4,  3],
        [16, 67, 69]]),
 array([[60, 85, 16],
        [69,  4, 67],
        [96,  3, 69]]))

Q2) Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array.

Ans)

In [44]:
# Generate a 1D NumPy array with 10 elements
array_1d = np.arange(10)

# Reshape it into a 2x5 array
array_2x5 = array_1d.reshape(2, 5)

# Reshape it into a 5x2 array
array_5x2 = array_2x5.reshape(5, 2)

array_1d, array_2x5, array_5x2


(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([[0, 1, 2, 3, 4],
        [5, 6, 7, 8, 9]]),
 array([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]]))

Q3)  Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

Ans)

In [46]:
# Create a 4x4 NumPy array with random float values
array_4x4 = np.random.rand(4, 4)

# Add a border of zeros around the 4x4 array to make it a 6x6 array
array_6x6 = np.pad(array_4x4, pad_width=1, mode='constant', constant_values=0)

array_4x4, array_6x6


(array([[0.10271336, 0.29754167, 0.05206862, 0.55695582],
        [0.66697611, 0.11960796, 0.42464748, 0.86661192],
        [0.83316294, 0.92463977, 0.80935841, 0.25384755],
        [0.24308174, 0.09726468, 0.54619848, 0.73924417]]),
 array([[0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ],
        [0.        , 0.10271336, 0.29754167, 0.05206862, 0.55695582,
         0.        ],
        [0.        , 0.66697611, 0.11960796, 0.42464748, 0.86661192,
         0.        ],
        [0.        , 0.83316294, 0.92463977, 0.80935841, 0.25384755,
         0.        ],
        [0.        , 0.24308174, 0.09726468, 0.54619848, 0.73924417,
         0.        ],
        [0.        , 0.        , 0.        , 0.        , 0.        ,
         0.        ]]))

Q4) Using NumPy, create an array of integers from 10 to 60 with a step of 5.

Ans)

In [50]:
import numpy as np

array = np.arange(10, 61, 5)
print(array)


[10 15 20 25 30 35 40 45 50 55 60]


Q5) Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations  (uppercase, lowercase, title case, etc.) to each element.

Ans) 

In [52]:
import numpy as np

# Create a NumPy array of strings
arr = np.array(['python', 'numpy', 'pandas'])

# Apply different case transformations
uppercase = np.char.upper(arr)
lowercase = np.char.lower(arr)
titlecase = np.char.title(arr)
capitalize = np.char.capitalize(arr)

# Display the results
print("Original:", arr)
print("Uppercase:", uppercase)
print("Lowercase:", lowercase)
print("Title Case:", titlecase)
print("Capitalize:", capitalize)


Original: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title Case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']


Q6)  Generate a NumPy array of words. Insert a space between each character of every word in the array.

Ans) 

In [54]:
import numpy as np

# Create a NumPy array of words
words = np.array(['hello', 'world', 'numpy', 'array'])
spaced_words = np.char.join(' ', words)

print(spaced_words)


['h e l l o' 'w o r l d' 'n u m p y' 'a r r a y']


Q7)  Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

Ans) 

In [56]:
import numpy as np

array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])
addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:\n", array1)
print("Array 2:\n", array2)
print("Addition:\n", addition)
print("Subtraction:\n", subtraction)
print("Multiplication:\n", multiplication)
print("Division:\n", division)


Array 1:
 [[1 2 3]
 [4 5 6]]
Array 2:
 [[ 7  8  9]
 [10 11 12]]
Addition:
 [[ 8 10 12]
 [14 16 18]]
Subtraction:
 [[-6 -6 -6]
 [-6 -6 -6]]
Multiplication:
 [[ 7 16 27]
 [40 55 72]]
Division:
 [[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


Q8) Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

Ans) 

In [58]:
import numpy as np

# Create a 5x5 identity matrix
identity_matrix = np.eye(5)

# Extract the diagonal elements
diagonal_elements = np.diag(identity_matrix)

print("Identity Matrix:\n", identity_matrix)
print("Diagonal Elements:", diagonal_elements)


Identity Matrix:
 [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
Diagonal Elements: [1. 1. 1. 1. 1.]


Q9) Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in  this array.

Ans)

In [60]:
import numpy as np

# Generate an array of 100 random integers between 0 and 1000
random_integers = np.random.randint(0, 1000, size=100)

# Function to check if a number is prime
def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(n**0.5) + 1):
        if n % i == 0:
            return False
    return True

# Find all prime numbers in the array
prime_numbers = [num for num in random_integers if is_prime(num)]

print("Random Integers:\n", random_integers)
print("Prime Numbers:\n", prime_numbers)


Random Integers:
 [916  57 542 823  32 916 728 787 346  82 823 996  98 822 175  95 182 607
 444 701 772 811 830 974 631 496 717 829 370 770 726 612 824 639 251 844
 241 730 209 213 507 941 770 715 292 332 673 229 392 722 130 299 579 411
 150 847 559 883 625 688 601 386 851 158 263 412 410   7 608 485  44 961
 193 704 626 796 837 970 826 871 957 647 902 596 422 564 672 615 432 521
 440 314 297 390 300 165 309 278 266 558]
Prime Numbers:
 [823, 787, 823, 607, 701, 811, 631, 829, 251, 241, 941, 673, 229, 883, 601, 263, 7, 193, 647, 521]


Q10)  Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

Ans)  

In [68]:
import numpy as np

daily_temperatures = np.random.randint(20, 36, size=30)

# Calculate weekly averages (6 days for the first 4 weeks and 2 days for the last week)
weekly_averages = [
    daily_temperatures[i:i+7].mean() for i in range(0, 30, 7)
]

print("Daily Temperatures:\n", daily_temperatures)
print("Weekly Averages:\n", weekly_averages)

Daily Temperatures:
 [22 21 22 21 29 35 30 28 24 28 35 32 24 34 22 21 21 33 28 32 31 30 27 33
 23 28 30 31 23 24]
Weekly Averages:
 [25.714285714285715, 29.285714285714285, 26.857142857142858, 28.857142857142858, 23.5]
